import json

descriptions = {
    "Two Sum": "Given an array of integers and a target sum.\nFind the indices of the two numbers that add up to the target.\nHint: Use a hash map to store seen values for O(n) time complexity.",
    "Valid Anagram": "Determine if two strings contain the exact same characters in any order.\nA classic string manipulation and frequency counting problem.\nHint: Use a hash map or an array of size 26 to count character frequencies.",
    "Contains Duplicate": "Check if any value appears at least twice in the array.\nThis is a fundamental problem to test your understanding of sets.\nHint: A hash set will give you O(n) time and space complexity.",
    "Group Anagrams": "Given an array of strings, group the anagrams together.\nYou need to find a unique representation for each set of anagrams.\nHint: Sort each string or use character counts as a dictionary key.",
    "Top K Frequent Elements": "Find the k most frequent elements in an integer array.\nTests your ability to use heaps or bucket sort algorithms.\nHint: Count frequencies first, then use a max-heap or bucket array.",
    "Valid Palindrome": "Check if a string reads the same forwards and backwards.\nYou should ignore non-alphanumeric characters and case.\nHint: Use two pointers starting from both ends moving towards the center.",
    "3Sum": "Find all unique triplets in an array that sum up to zero.\nA step up from Two Sum, requiring careful handling of duplicates.\nHint: Sort the array first, then use a loop with two pointers.",
    "Container With Most Water": "Find two lines that together with the x-axis form a container holding the most water.\nA classic optimization problem using the two-pointer technique.\nHint: Start pointers at the ends and move the one with the smaller height.",
    "Trapping Rain Water": "Calculate how much water can be trapped between elevation maps after raining.\nA challenging problem that tests your understanding of arrays and boundaries.\nHint: Use two pointers or precompute the max heights from left and right.",
    "Two Sum II - Input Array Is Sorted": "Find two numbers that add up to a target in a 1-indexed sorted array.\nYou must use only constant extra space.\nHint: Since it is sorted, use two pointers from the start and end.",
    "Valid Parentheses": "Determine if a string of brackets is well-formed and closed in the correct order.\nThe quintessential stack problem.\nHint: Push opening brackets onto a stack and pop when matching closing brackets.",
    "Min Stack": "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.\nTests your ability to augment standard data structures.\nHint: Store tuples of (value, current_min) in your stack.",
    "Daily Temperatures": "Find how many days you have to wait until a warmer temperature.\nA great introduction to monotonic stacks.\nHint: Keep a stack of indices for temperatures you haven't found a warmer day for.",
    "Generate Parentheses": "Generate all combinations of n pairs of well-formed parentheses.\nA classic backtracking problem.\nHint: Keep track of the number of open and closed brackets you have used.",
    "Largest Rectangle in Histogram": "Find the area of the largest rectangle in a histogram.\nA difficult problem that optimally uses a monotonic stack.\nHint: Maintain a stack of indices in increasing order of heights.",
    "Binary Search": "Find a target integer in a sorted array in O(log n) time.\nThe foundational algorithm for searching sorted data.\nHint: Maintain left and right pointers and check the middle element.",
    "Search in Rotated Sorted Array": "Find a target in a sorted array that has been pivoted at an unknown point.\nRequires modifying the standard binary search logic.\nHint: Determine which half of the array is properly sorted first.",
    "Find Minimum in Rotated Sorted Array": "Find the smallest element in a rotated sorted array in O(log n) time.\nA variation of binary search focusing on inflection points.\nHint: Compare the middle element with the rightmost element to find the dip.",
    "Koko Eating Bananas": "Find the minimum eating speed to finish all bananas within h hours.\nA classic 'binary search on the answer' problem.\nHint: The minimum speed is 1 and the maximum is the largest pile.",
    "Median of Two Sorted Arrays": "Find the median of two sorted arrays in O(log(m+n)) time.\nOne of the most challenging binary search problems.\nHint: Binary search on the smaller array to find the correct partition.",
    "Best Time to Buy and Sell Stock": "Maximize your profit by choosing a single day to buy and a single day to sell.\nA fundamental problem for sliding window / dynamic programming.\nHint: Keep track of the minimum price seen so far and the max profit.",
    "Longest Substring Without Repeating Characters": "Find the length of the longest substring without repeating characters.\nThe quintessential sliding window problem.\nHint: Use a set or map to track characters in the current window.",
    "Minimum Window Substring": "Find the minimum window in a string containing all characters of another string.\nA hard sliding window problem requiring careful frequency counting.\nHint: Expand the right pointer to find a valid window, then shrink from the left.",
    "Longest Repeating Character Replacement": "Find the longest substring containing the same letter after at most k replacements.\nTests your ability to maintain window state efficiently.\nHint: The window is valid if (length - max_freq_char_count) <= k.",
    "Sliding Window Maximum": "Find the maximum in every sliding window of size k in an array.\nA hard problem optimally solved with a deque.\nHint: Maintain a decreasing monotonic queue of indices.",
    "Reverse Linked List": "Reverse a singly linked list.\nThe most fundamental linked list manipulation problem.\nHint: Use three pointers: prev, curr, and next.",
    "Merge Two Sorted Lists": "Merge two sorted linked lists into one sorted list.\nA classic algorithm that forms the basis of merge sort.\nHint: Use a dummy head node and iteratively attach the smaller node.",
    "Linked List Cycle": "Determine if a linked list has a cycle in it.\nA famous problem testing the slow and fast pointer technique.\nHint: Floyd's Cycle-Finding Algorithm (Tortoise and Hare).",
    "Reorder List": "Reorder a linked list to alternate between the first and last halves.\nCombines finding the middle, reversing a list, and merging.\nHint: Use fast/slow pointers to find the mid, then reverse the second half.",
    "Merge k Sorted Lists": "Merge k sorted linked lists into one sorted list.\nA hard problem that combines linked lists with priority queues.\nHint: Use a min-heap to keep track of the current smallest node among all lists.",
    "Binary Tree Level Order Traversal": "Return the level order traversal of a binary tree's nodes' values.\nThe quintessential Breadth-First Search (BFS) problem for trees.\nHint: Use a queue to process nodes level by level.",
    "Maximum Depth of Binary Tree": "Find the maximum depth of a binary tree.\nA fundamental Depth-First Search (DFS) or BFS problem.\nHint: The depth is 1 + max(left_depth, right_depth).",
    "Lowest Common Ancestor of a Binary Search Tree": "Find the lowest common ancestor of two nodes in a BST.\nUtilizes the core property of Binary Search Trees.\nHint: If both values are greater/less than the root, go right/left.",
    "Binary Tree Maximum Path Sum": "Find the maximum path sum in a binary tree (any node to any node).\nA challenging DFS problem requiring post-order traversal.\nHint: At each node, compute the max path going straight down, but update a global max with the split path.",
    "Serialize and Deserialize Binary Tree": "Design an algorithm to serialize and deserialize a binary tree.\nTests your ability to represent tree structures as strings.\nHint: Pre-order traversal with a special marker for null nodes works well.",
    "Kth Largest Element in an Array": "Find the kth largest element in an unsorted array.\nCan be solved with sorting, heaps, or QuickSelect.\nHint: A min-heap of size k is an optimal solution.",
    "K Closest Points to Origin": "Find the k closest points to the origin (0, 0).\nA classic priority queue problem involving geometry.\nHint: Use a max-heap of size k based on the distance formula.",
    "Task Scheduler": "Find the minimum intervals required to finish all tasks with a cooldown period.\nA tricky greedy/heap problem requiring careful counting.\nHint: Focus on scheduling the most frequent tasks first.",
    "Find Median from Data Stream": "Design a data structure that supports adding numbers and finding the median.\nA hard design problem optimally solved with two heaps.\nHint: Maintain a max-heap for the lower half and a min-heap for the upper half.",
    "Subsets": "Find all possible subsets (the power set) of a unique integer array.\nThe most basic backtracking/combinatorics problem.\nHint: At each step, you can either include the current element or exclude it.",
    "Combination Sum": "Find all unique combinations of candidates where the chosen numbers sum to target.\nA backtracking problem where elements can be reused.\nHint: Subtract the candidate from the target and recurse.",
    "Permutations": "Given an array of distinct integers, return all the possible permutations.\nA classic backtracking problem for generating all arrangements.\nHint: Swap elements or keep a boolean array of used elements.",
    "Word Search": "Given a grid of characters, find if a word exists in it (horizontally/vertically).\nA standard DFS backtracking problem on a 2D matrix.\nHint: Temporarily modify the board to mark visited cells to avoid revisiting.",
    "N-Queens": "Place n queens on an n x n chessboard such that no two queens attack each other.\nThe quintessential complex backtracking puzzle.\nHint: Maintain sets for occupied columns, positive diagonals, and negative diagonals.",
    "Implement Trie (Prefix Tree)": "Design a Trie data structure supporting insert, search, and startsWith.\nThe foundational problem for understanding prefix trees.\nHint: Each node should contain an array/map of children and a boolean 'is_end' flag.",
    "Design Add and Search Words Data Structure": "Design a data structure that adds words and searches with '.' as a wildcard.\nA slightly more complex Trie problem requiring DFS.\nHint: If you encounter a '.', recursively check all possible child nodes.",
    "Word Search II": "Find all words from a dictionary that are present in a 2D board.\nA hard problem combining DFS on a grid with a Trie.\nHint: Build a Trie from the dictionary and traverse the grid, pruning paths not in the Trie.",
    "Longest Common Prefix": "Find the longest common prefix string amongst an array of strings.\nA straightforward string manipulation problem.\nHint: Compare characters at the same index across all strings until a mismatch occurs.",
    "Replace Words": "Replace words in a sentence with their shortest root from a dictionary.\nAn excellent application of a Trie for fast prefix matching.\nHint: Insert all roots into a Trie and find the shortest prefix for each word.",
    "Number of Islands": "Count the number of islands (connected 1s) in a 2D grid.\nThe classic graph traversal problem for grids.\nHint: Iterate through the grid and launch a DFS/BFS to sink each island you find.",
    "Clone Graph": "Return a deep copy of a connected undirected graph.\nTests your ability to traverse graphs and manage object references.\nHint: Use a hash map to map original nodes to their cloned counterparts.",
    "Pacific Atlantic Water Flow": "Find cells where water can flow to both the Pacific and Atlantic oceans.\nA grid traversal problem starting from the boundaries.\nHint: Run DFS/BFS from the ocean borders inwards to find reachable cells.",
    "Course Schedule": "Determine if you can finish all courses given prerequisite pairs.\nA classic topological sort / cycle detection problem.\nHint: Build a directed graph and check for cycles using DFS or Kahn's algorithm.",
    "Word Ladder": "Find the shortest transformation sequence from a begin word to an end word.\nA shortest path problem optimally solved with BFS.\nHint: Build an adjacency list using wildcards (e.g., 'h*t') to connect similar words.",
    "Network Delay Time": "Find the time it takes for a signal to reach all nodes in a network.\nA classic shortest path problem on a weighted graph.\nHint: Use Dijkstra's Algorithm with a min-heap.",
    "Min Cost to Connect All Points": "Find the minimum cost to connect all points on a 2D plane.\nThe quintessential Minimum Spanning Tree (MST) problem.\nHint: Use Prim's or Kruskal's algorithm.",
    "Cheapest Flights Within K Stops": "Find the cheapest price from a source to destination with at most k stops.\nA variation of shortest path that adds a constraint on the number of edges.\nHint: Use Bellman-Ford or a modified Dijkstra's/BFS tracking steps.",
    "Swim in Rising Water": "Find the minimum time needed to reach the bottom-right square of a grid.\nA pathfinding problem combining grids and priority queues.\nHint: Use Dijkstra's algorithm, maintaining the max elevation seen on the path.",
    "Reconstruct Itinerary": "Reconstruct a travel itinerary from a list of airline tickets.\nA challenging problem based on finding an Eulerian path.\nHint: Build a graph with sorted destinations and do a post-order DFS.",
    "Climbing Stairs": "Find the number of distinct ways to climb n stairs taking 1 or 2 steps.\nThe 'Hello World' of dynamic programming.\nHint: The solution is identical to computing the Fibonacci sequence.",
    "House Robber": "Find the maximum amount of money you can rob from houses without robbing adjacent ones.\nA fundamental 1D dynamic programming problem.\nHint: At each house, you decide to either rob it (plus dp[i-2]) or skip it (dp[i-1]).",
    "Coin Change": "Find the minimum number of coins needed to make up a given amount.\nA classic unbounded knapsack problem.\nHint: Build up the solution from amount 0 up to the target amount.",
    "Longest Increasing Subsequence": "Find the length of the longest strictly increasing subsequence in an array.\nA core dynamic programming concept that can also be solved with binary search.\nHint: dp[i] represents the length of the LIS ending at index i.",
    "Word Break": "Determine if a string can be segmented into a space-separated sequence of dictionary words.\nA 1D DP problem testing string matching and state.\nHint: dp[i] is true if the string up to index i can be segmented.",
    "Unique Paths": "Find the number of possible unique paths from top-left to bottom-right of a grid.\nThe fundamental 2D dynamic programming problem.\nHint: The number of paths to a cell is the sum of paths to the cell above it and left of it.",
    "Longest Common Subsequence": "Find the length of the longest common subsequence between two strings.\nA classic 2D DP problem comparing two sequences.\nHint: Build a 2D DP table where dp[i][j] represents the LCS up to indices i and j.",
    "Edit Distance": "Find the minimum operations to convert one string to another.\nA famous DP problem used in spell checkers and genetics.\nHint: Operations are insert, delete, and replace. Map them to your DP transitions.",
    "Burst Balloons": "Find the maximum coins you can collect by bursting balloons.\nA very challenging DP problem that requires thinking in reverse.\nHint: dp[i][j] represents the max coins obtained by bursting balloons between i and j.",
    "Regular Expression Matching": "Implement regular expression matching with support for '.' and '*'.\nA difficult string parsing problem optimally solved with 2D DP.\nHint: Carefully handle the '*' character, which can represent zero or more of the preceding element.",
    "Jump Game": "Determine if you can reach the last index of an array.\nA classic greedy problem.\nHint: Keep track of the maximum reachable index as you iterate.",
    "Jump Game II": "Find the minimum number of jumps to reach the last index.\nA greedy problem requiring you to track the current jump boundaries.\nHint: Maintain the farthest index reachable in the current jump and the next jump.",
    "Gas Station": "Find the starting gas station's index if you can travel around the circuit once.\nA greedy problem that requires single-pass optimization.\nHint: If total gas >= total cost, a solution exists. Keep track of the current tank deficit.",
    "Partition Labels": "Partition a string into as many parts as possible so each letter appears in at most one part.\nA greedy problem involving character last-occurrence indices.\nHint: Record the last occurrence of each character, then iterate and update the partition boundary.",
    "Non-overlapping Intervals": "Find the minimum number of intervals you need to remove to make the rest non-overlapping.\nA greedy interval scheduling problem.\nHint: Sort by end times and always pick the interval that ends earliest.",
    "Merge Intervals": "Merge all overlapping intervals into an array of non-overlapping intervals.\nThe foundational problem for interval manipulation.\nHint: Sort intervals by start time and merge if the next start <= current end.",
    "Insert Interval": "Insert a new interval into a list of non-overlapping intervals and merge if necessary.\nA slightly trickier interval problem requiring careful ordering.\nHint: Iterate and handle three cases: entirely before, entirely after, or overlapping.",
    "Meeting Rooms": "Determine if a person could attend all meetings (no overlapping intervals).\nA basic interval scheduling problem.\nHint: Sort the intervals by start time and check if any start time is less than the previous end time.",
    "Minimum Interval to Include Each Query": "Find the size of the smallest interval containing each query point.\nA challenging problem combining intervals, sorting, and priority queues.\nHint: Sort queries and intervals. Use a min-heap to keep track of valid interval sizes.",
    "Single Number": "Find the single element in an array where every other element appears twice.\nA classic bit manipulation trick problem.\nHint: XOR all elements together; duplicates will cancel each other out.",
    "Number of 1 Bits": "Write a function that takes an unsigned integer and returns the number of '1' bits.\nA fundamental bitwise operations test.\nHint: Use the trick n & (n - 1) to clear the lowest set bit.",
    "Counting Bits": "Return an array of the number of 1's in the binary representation of numbers from 0 to n.\nA DP problem based on bit manipulation.\nHint: The number of bits for n is the number of bits for n/2 plus n % 2.",
    "Reverse Bits": "Reverse the bits of a 32-bit unsigned integer.\nA bit manipulation problem requiring shifting and masking.\nHint: Extract bits one by one and shift them into the reversed result.",
    "Sum of Two Integers": "Calculate the sum of two integers without using the operators + and -.\nA computer architecture problem simulating an adder with bitwise logic.\nHint: Use XOR for addition without carry, and AND with left shift for the carry.",
    "Rotate Image": "Rotate an n x n 2D matrix 90 degrees clockwise in-place.\nA tricky matrix manipulation problem.\nHint: First transpose the matrix (swap symmetry), then reverse each row.",
    "Spiral Matrix": "Return all elements of an m x n matrix in spiral order.\nA simulation problem requiring careful boundary management.\nHint: Keep track of top, bottom, left, and right boundaries and shrink them as you go.",
    "Set Matrix Zeroes": "If an element is 0, set its entire row and column to 0 in-place.\nA matrix problem requiring space optimization.\nHint: Use the first row and first column to keep track of which rows and columns need to be zeroed.",
    "Happy Number": "Determine if a number is 'happy' (sum of squares of digits eventually reaches 1).\nA math and cycle detection problem.\nHint: Use a hash set to track seen numbers, or Floyd's Cycle-Finding Algorithm.",
    "Pow(x, n)": "Calculate x raised to the power n.\nA math problem requiring an efficient O(log n) algorithm.\nHint: Use binary exponentiation: x^n = (x^2)^(n/2)."
}

with open('questions.json', 'r') as f:
    questions = json.load(f)

for q in questions:
    title = q['title']
    if title in descriptions:
        q['description'] = descriptions[title]
    else:
        q['description'] = f"A classic problem testing your algorithmic skills in {q['topic']}.\nUnderstand the edge cases and optimize for time and space.\nHint: Think about standard data structures used for {q['topic']}."

with open('questions.json', 'w') as f:
    json.dump(questions, f, indent=4)
print("Updated questions.json with 3-line descriptions.")
